### ISSUE TITLE
You can use User::find()

### ISSUE THREAD

**Issue by alexmanase** [catabozan/laravel-project#2]
https://github.com/catabozan/laravel-project/blob/1594ef52c47ae98632e9090352ca92f7efcaee99/app/Http/Controllers/AccountController.php#L51

See: https://laravel.com/docs/8.x/eloquent#retrieving-single-models

**Comment by catabozan** [comment]
line removed with this commit: 0e71cf188bcfdc13b96a2dc0c1447fa2ad49ea51
