### ISSUE TITLE
Use a request class

### ISSUE THREAD

**Issue by alexmanase** [catabozan/laravel-project#4]
https://github.com/catabozan/laravel-project/blob/1594ef52c47ae98632e9090352ca92f7efcaee99/app/Http/Controllers/AccountController.php#L56-L60

See: https://laravel.com/docs/8.x/validation#creating-form-requests

**Comment by catabozan** [comment]
fixed with this commit: 0e71cf188bcfdc13b96a2dc0c1447fa2ad49ea51
