### ISSUE TITLE
Make the `web.php` shorter

### ISSUE THREAD

**Issue by alexmanase** [catabozan/laravel-project#5]
https://github.com/catabozan/laravel-project/blob/1594ef52c47ae98632e9090352ca92f7efcaee99/routes/web.php#L21-L27

1. https://laravel.com/docs/8.x/routing#route-group-prefixes
2. https://laravel.com/docs/8.x/routing#route-group-name-prefixes

**Comment by catabozan** [comment]
fixed with this commit: 51c8c7ffa8db13590f85dce7175035cbed794196
